#!/bin/bash

# This file was taken from https://gist.github.com/wolf6101/f1857a41f5898328b7e5eef2686974b9

# Check if the MERGE_HEAD file is present, indicating that a merge is being performed
if [ -f ".git/MERGE_HEAD" ]
then
    exit 0
fi

BRANCH_NAME=$(git branch --show-current)  ## $(git branch | grep '*' | sed 's/* //')

# Get the commit message, removing lines that start with a #
MESSAGE=$(cat "$1" | sed '/^#.*/d')

# Check if the commit message is non-empty
if [ -n "$MESSAGE" ]
then
    # Add the branch name and the commit message to the commit message file
    echo -e "$BRANCH_NAME: $MESSAGE" > "$1"
else
    echo "Aborting commit due to empty commit message."
    exit 1
fi